---
- name: Playbook for creating ec2 and route 53 records
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    names:
      - web
      - mongodb
      - catalogue
      - redis
      - user
      - cart
      - mysql
      - shipping
      - rabbitmq
      - payments
      - dispatch

  tasks:
    - name: Create mongodb and mysql of type t3.meduim
      ec2:
        region: us-east-1
        instance_type: t3.medium
        image: ami-03265a0778a880afb
        count: "{{ (names|length)-9 }}"
        group_id: sg-0e658def150f1a79a
        instance_tags:
          Name: "{{ item }}"
      with_items: "{{ names }}"
      when: item == "mongodb" or item == "mysql"
    - name: Create other instances with type of t3.micro
      ec2:
        region: us-east-1
        instance_type: t3.micro
        image: ami-03265a0778a880afb
        count: "{{ (names|length)-2 }}"
        group_id: sg-0e658def150f1a79a
        instance_tags:
          Name: "{{ item }}"
      with_items: "{{ names }}"
      when: item != "mongodb" or item != "mysql"